name: Accent push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace secret in accent.json
        run: sed -i 's/%ACCENT_APIKEY%/${{ secrets.ACCENT_APIKET }}/g' accent.json
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g accent-cli
      - run: accent sync --add-translations --merge-type=passive